# master: api & console
- name: Update DNS for master elb
  route53:
    state: present
    type: CNAME
    zone: "{{ item.zone }}"
    value: "{{ l_openshift_aws_elb_facts[openshift_clusterid + '-master-external']['dns_name'] }}"
    record: "{{ item.fqdn }}"
    ttl: 120
  with_items:
  - zone: opentry.me
    fqdn: "{{ openshift_clusterid }}.opentry.me"


# master internal: api
- name: Update DNS for master internal ELB
  route53:
    state: present
    type: CNAME
    zone: "{{ item.zone }}"
    value: "{{ l_openshift_aws_elb_facts[openshift_clusterid + '-master-internal']['dns_name'] }}"
    record: "{{ item.fqdn }}"
    ttl: 120
  with_items:
  - zone: opentry.me
    fqdn: "api.{{ openshift_clusterid }}.opentry.me"

# infra: route
- name: Update DNS for infra ELB
  route53:
    state: present
    type: CNAME
    zone: "{{ item.zone }}"
    value: "{{ l_openshift_aws_elb_facts[openshift_clusterid + '-infra']['dns_name'] }}"
    record: "{{ item.fqdn }}"
    ttl: 120
  with_items:
  - zone: opentry.me
    fqdn: "*.apps.{{ openshift_clusterid )).opentry.me"