# master: api & console
- name: Update DNS for master elb
  route53:
    state: present
    type: CNAME
    zone: "{{ domain}}"
    value: "{{ l_openshift_aws_elb_facts[openshift_clusterid + '-master-external']['dns_name'] }}"
    record: "{{ openshift_clusterid }}.{{ domain }}"
    aws_access_key: "{{ dns_access_key | default(aws_access_key) }}"
    aws_secret_key: "{{ dns_secret_key | default(aws_secret_key) }}"
    ttl: 120


# master internal: api
- name: Update DNS for master internal ELB
  route53:
    state: present
    type: CNAME
    zone: "{{ domain }}"
    value: "{{ l_openshift_aws_elb_facts[openshift_clusterid + '-master-internal']['dns_name'] }}"
    record: "api.{{ openshift_clusterid }}.{{ domain}}"
    aws_access_key: "{{ dns_access_key | default(aws_access_key) }}"
    aws_secret_key: "{{ dns_secret_key | default(aws_secret_key) }}"
    ttl: 120

# infra: route
- name: Update DNS for infra ELB
  route53:
    state: present
    type: CNAME
    zone: "{{ domain }}"
    value: "{{ l_openshift_aws_elb_facts[openshift_clusterid + '-infra']['dns_name'] }}"
    record: "*.apps.{{ openshift_clusterid }}.{{ domain }}"
    aws_access_key: "{{ dns_access_key | default(aws_access_key) }}"
    aws_secret_key: "{{ dns_secret_key | default(aws_secret_key) }}"
    ttl: 120
